FROM python:3.10-slim
RUN python3.10 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /opt/code/api
COPY requirements.txt .
RUN /opt/venv/bin/pip install --no-cache-dir -r requirements.txt
COPY /processing  /opt/code/processing
COPY /api         /opt/code/api
COPY processing.py /opt/code/
ENV PYTHONPATH="/opt/code"
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]